version: '2.1'


### GPU Monitoring
services:
  watchtower:
    image: v2tec/watchtower:latest
    command: --cleanup --label-enable --schedule="0 2 * * *"
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  gpu_pushgateway:
    image: prom/pushgateway
    container_name: gpu_pushgateway
    hostname: gpu_pushgateway
    ports:
      - "9091:9091"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /etc/prometheus/prometheus.yml:/tmp/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    ports:
      - "3000:3000"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped

